In [ ]:
import os
from datetime import datetime

# моя БД, в которую сохраняем кастомные распарсенные данные
host_mssql = 'REGRU-54856\MSSQLSERVER01'
port_mssql = '1433'

# название БД одно и тоже в MySQL и MSSQL
db_name = 'mediascope_x5'


start_date = '2023-01-01' 

cred_path = r'C:\Users\o.bogomolov\Desktop\Jupyter_notebook\42_02_Mediascope_Nat_tv_Ratings\cred'
full_cleaning_link = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSpOdyJw-_MOFGAeyC2GHVJCl7DnIgygfzOcxsFq1Tr7N1UBfDZfhAKiIQ4DF34OA/pub?gid=902178034&single=true&output=csv'
discounts_link = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTeV7y_TRGzF1gZvlyz43hhtYq_v_-9URsPVT-TdoGLebYZcLHgH83EAzqCAj1OhN9wHfFLMu3_DSzz/pub?gid=0&single=true&output=csv'

In [ ]:
# Функция для того, чтобы объеденить все элементы списка в одну строку
# это нужно для условий фильтрации в условиях запроса TV_index
def get_lst_to_str(lst):
    return ', '.join(str(elem) for elem in lst)

In [ ]:
# Здесь передаем список ИД для фильтрации по ad_filter 
# Услоия этого фильтра представлены в строке ниже
article_lev_4_id_lst = [2408, 4780, 4926, 5028]
article_lev_4_id_str = get_lst_to_str(article_lev_4_id_lst)

subbrand_id_lst = [311419, 393963, 461753, 463018, 586043, 651039, 689003, 719137]
subbrand_id_str = get_lst_to_str(subbrand_id_lst)

In [ ]:
# Здесь прописываем логические условия ad_filter 
# Они применяются для получения статистики в отчетах Simple и Buying
nat_tv_ad_filter = f'articleLevel4Id IN ({article_lev_4_id_str}) or subbrandListId IN ({subbrand_id_str})'

In [ ]:
# # Срезы для отчета Simple и Buying по сути одинаковые
# # Поэтому задаем их только 1 раз здесь
# # ЗДЕСЬ НИЧЕГО НЕ МЕНЯЕМ 
# # эти срезы зашиты в таблицы БД, если их изменить
# # Создаем список срезов по Nat_tv
# # Указываем список срезов - в задаче не может быть больше 25 срезов
# nat_tv_slices = [
#     'advertiserListName', 
#     'brandListName', 
#     'subbrandListName', 
#     'modelListName',
#     'articleList2Name',
#     'articleList3Name',
#     'articleList4Name', 
#     'adId',
#     'adName',
#     'adNotes',
#     'adFirstIssueDate',
#     'adSloganAudioName',
#     'adSloganVideoName',
#     'researchDate',
#     'regionName',
#     'adDistributionTypeName',
#     'tvNetName',
#     'tvCompanyName',
#     'tvCompanyId',
#     'adTypeName',
#     'adStandardDuration', 
#     'adPositionTypeName',
#     'adPrimeTimeStatusName',
#     'adStartTime',
#     'adSpotId'
#          ]

In [28]:
# Срезы для отчета Simple и Buying по сути одинаковые
# Поэтому задаем их только 1 раз здесь
# ЗДЕСЬ НИЧЕГО НЕ МЕНЯЕМ 
# эти срезы зашиты в таблицы БД, если их изменить
# Создаем список срезов по Nat_tv
# Указываем список срезов - в задаче не может быть больше 25 срезов
nat_tv_slices = [
    'advertiserListId', #Список рекламодателей id
    # 'advertiserListName', 
    'brandListId', #Список брендов id
    # 'brandListName', 
    'subbrandListId', #Список суббрендов id
    # 'subbrandListName', 
    'modelListId', #Список продуктов id
    # 'modelListName',
    'articleList2Id', #Список товарных категорий 2 id
    # 'articleList2Name',
    'articleList3Id', #Список товарных категорий 3 id
    # 'articleList3Name',
    'articleList4Id', #Список товарных категорий 4 id
    # 'articleList4Name', 
    'adId',
    # 'adName',
    'adNotes',
    'adFirstIssueDate',
    'adSloganAudioId', #Ролик аудио слоган id
    # 'adSloganAudioName',
    'adSloganVideoId', #Ролик видео слоган id
    # 'adSloganVideoName',
    'researchDate',
    # 'regionId', # ИД Региона или Сетевое вещание
    'regionName',
    'adDistributionTypeName',
    # 'tvNetId', # id телесети
    'tvNetName',
    'tvCompanyId',
    # 'tvCompanyName',
    'adTypeId', #Ролик тип ID 
    # 'adTypeName',
    'adStandardDuration', 
    # 'adPositionType', #Ролик позиционирование id 
    'adPositionTypeName',
    # 'adPrimeTimeStatusId', #Прайм/ОфПрайм роликов id
    'adPrimeTimeStatusName',
    'adStartTime',
    'adSpotId'
         ]

In [ ]:
# Указываем список статистик для расчета
# Статистики для отчета Simple
nat_tv_simple_statistics =['Rtg000', 'RtgPer', 'StandRtgPer', 'Quantity', 'ConsolidatedCostRUB'] 

# Статистики для отчета Buying
nat_tv_bying_statistics = ['SalesRtgPer', 'StandSalesRtgPer']

In [ ]:
# Задаем опции расчета
nat_tv_options = {
    "kitId": 1, # набора данных (1-Russia all, 2-Russia 100+, 3-Cities, # 4-TVI+ Russia all, 5-TVI+ Russia 100+, 6-Moscow) 
    # "totalType": "TotalChannels" #база расчета тотал статистик: Total Channels. Возможны опции: TotalTVSet, TotalChannelsThem
    "standRtg" : {
      "useRealDuration" : False,
      "standardDuration" : 20
    }
}

In [ ]:
# Задаем все демографические группы, чтобы каждую из них вывести в отдельном поле
# Задаем необходимые группы

# targets = {
# 'W 25-54'       :'sex = 2 AND age >= 25 AND age <= 54',
# 'All 18-64'     :'age >= 18 AND age <= 64',
# 'M 25-45 BC'    :'sex = 1 AND age >= 25 AND age <= 45 AND incomeGroupRussia IN (2,3)',
# 'ALL'           :'age >= 4'
# }

# все 25-45, все 25-55, все 25+, все 25-45 BC, все 25-55 BC, ж 25-44, все 20-50, все 20-50 BC, все 20-55, w25+
# Доход по группе A,B,C

nat_tv_targets = {
'ALL 25-45'     :'age >= 25 AND age <= 45',
'All 25-55'     :'age >= 25 AND age <= 55',
'ALL 25+'       :'age >= 25',
'ALL 25-54 BC'  :'age >= 25 AND age <= 54 AND incomeGroupRussia IN (2,3)',
'W 25-44'       :'sex = 2 AND age >= 25 AND age <= 44',
'All 20-50'     :'age >= 20 AND age <= 50',
'ALL 20-50 BC'  :'age >= 20 AND age <= 50 AND incomeGroupRussia IN (2,3)',
'All 20-55'     :'age >= 20 AND age <= 55',
'W 25+'         :'sex = 2 AND age >= 25',
'ABC'           :'incomeGroupRussia IN (1, 2,3)'
}

In [ ]:
# создаем функцию, чтобы забрать данные для подключения из текстового файла
def get_cred_dict(file_path, file_name):
    dict = {}
    creds = open(os.path.join(file_path, file_name), encoding='utf-8').read()
    for text in creds.split('\n'):
        content = text.split(': ')
        dict[content[0]] = content[1]

    return dict

In [ ]:
db_mssql_file = 'db_mssql_creds.txt'
db_mssql_dict = get_cred_dict(cred_path, db_mssql_file)

db_mssql_login = db_mssql_dict['login']
db_mssql_pass = db_mssql_dict['pass']

In [ ]:
# Справочник Объявлений с собственными названиями
# сотрудники ведут гугл докс с чисткой
# в этом же файле добавили новые поля с собственными группировками
# загружаем эту кастомную таблицу в БД, чтобы потом использовать в дашборде
custom_ad_dict = 'custom_ad_dict'

custom_ad_dict_vars_list = [
            'media_key_id nvarchar(40)',
            'media_type nvarchar(20)',
            'ad_id int',
            'advertiser_list nvarchar(150)',
            'brand_list nvarchar(300)',
            'subbrand_list nvarchar(300)',
            'model_list nvarchar(500)',
            'article_list_2 nvarchar(300)',
            'article_list_3 nvarchar(400)',
            'article_list_4 nvarchar(500)',
            'ad_name nvarchar(200)',
            'ad_description nvarchar(500)',
            'first_issue_date nvarchar(10)',
            'clip_type_region nvarchar(100)',
            'advertiser_type nvarchar(20)',
            'advertiser_main nvarchar(100)',
            'brand_main nvarchar(150)',
            'competitor nvarchar(20)',
            'category_general nvarchar(50)',
            'include_exclude nvarchar(15)',
            'delivery nvarchar(30)',
            'product_category nvarchar(50)',
            'cleaning_flag tinyint'
]

custom_ad_dict_int_lst = ['ad_id', 'cleaning_flag']

In [3]:
# словарь с характеристиками Объявлений
# забираем через отчет Simple

# пересоздаем пустую таблицу Справочников в БД
nat_tv_ad_dict = 'nat_tv_ad_dict'

nat_tv_ad_dict_vars_list = [
            'media_key_id nvarchar(40)',
            'media_type nvarchar(20)',
            'adId int',
            'adName nvarchar(200)',
            'advertiserListName nvarchar(150)',
            'brandListName nvarchar(150)',
            'subbrandListName nvarchar(300)',
            'articleList2Name nvarchar(300)',
            'articleList3Name nvarchar(400)',
            'articleList4Name nvarchar(500)',
            'modelListName nvarchar(500)',
            'adFirstIssueDate nvarchar(10)',
            'adSloganAudioName nvarchar(200)',
            'adSloganVideoName nvarchar(200)',
            'adNotes nvarchar(500)'
            ]

nat_tv_int_lst = ['adId']

In [9]:
# таблица фактов по отчету Simple

# При создании 2-х таблиц БД - отчет Simple / отчет Buying
# Большая Часть названий полей повторяется
# Чтобы сохранить последовательность, если потребуется быстро заменить какое-то поле в БД сразу в 3-х таблицах
# будем использовать список названий полей из Справочника - как базовый и в отчете Simple и Buying - просто добавим отличающиеся поля
nat_tv_simple = 'nat_tv_simple'

nat_tv_simple_vars_list = [
            'prj_name nvarchar(50)',
            'media_key_id nvarchar(40)',
            'media_type nvarchar(20)',
            'adId int',
            'researchDate nvarchar(10)',
            'regionName nvarchar(100)',
            'adDistributionTypeName nvarchar(30)',
            'tvNetName nvarchar(100)',
            'tvCompanyName nvarchar(100)',
            'adTypeName nvarchar(100)',
            'adStandardDuration int',
            'adPositionTypeName  nvarchar(50)',
            'adPrimeTimeStatusName nvarchar(50)',
            'adStartTime nvarchar(8)',
            'adSpotId bigint',
            'Rtg000 float',
            'RtgPer float',
            'StandRtgPer float',
            'Quantity int',
            'ConsolidatedCostRUB float',
            'ConsolidatedCostRUB_disc float'
]

nat_tv_simple_int_lst = ['adId', 'adStandardDuration', 'adSpotId', 'Quantity']
nat_tv_simple_float_lst = ['Rtg000', 'RtgPer', 'StandRtgPer', 'ConsolidatedCostRUB', 'ConsolidatedCostRUB_disc']

In [26]:
# таблица фактов по отчету Simple
nat_tv_buying = 'nat_tv_buying'

# Создаем список названий полей и типов данных для таблицы Buying в БД MSSQL
#  берем все поля из таблицы Simple и убрибаем из них метрики отчета Simple
# добавляем метрики отчета Buying
nat_tv_buying_vars_list = list(set(nat_tv_simple_vars_list) - 
set(['ConsolidatedCostRUB float', 'ConsolidatedCostRUB_disc', 'Quantity smallint', 'Rtg000 float', 'RtgPer float', 'StandRtgPer float'])) 
nat_tv_buying_vars_list = nat_tv_buying_vars_list + ['SalesRtgPer float', 'StandSalesRtgPer float']

nat_tv_buying_int_lst = ['adId', 'adStandardDuration', 'adSpotId']
nat_tv_buying_float_lst = ['SalesRtgPer', 'StandSalesRtgPer']